[build.environment]
HUGO_VERSION = "0.146.4"
NODE_VERSION = "22"
TZ = "Europe/Amsterdam"

[build]
publish = "public"
command = "hugo --gc --minify"

[context.production]
command = "hugo --minify"

[context.deploy-preview]
command = "hugo --baseURL $DEPLOY_PRIME_URL"
